# -*- coding: utf-8 -*-
"""Project B.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YGmC_I2gPIvGAVL2o37CyQ1l-8GrdfYQ
"""

import pandas as pd

url = "https://raw.githubusercontent.com/Chava-Sai/Artificial-Intelligence-Course/refs/heads/main/Day-21-EDA-Mini-Project/airlines.csv"

airlines = pd.read_csv(url)

airlines.head()

import pandas as pd

url = "https://raw.githubusercontent.com/Chava-Sai/Artificial-Intelligence-Course/refs/heads/main/Day-21-EDA-Mini-Project/flights.csv"

flights = pd.read_csv(url)

flights.head()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter("ignore")
airlines_url = "https://raw.githubusercontent.com/Chava-Sai/Artificial-Intelligence-Course/refs/heads/main/Day-21-EDA-Mini-Project/airlines.csv"
flights_url = "https://raw.githubusercontent.com/Chava-Sai/Artificial-Intelligence-Course/refs/heads/main/Day-21-EDA-Mini-Project/flights.csv"

airlines = pd.read_csv(airlines_url)
flights  = pd.read_csv(flights_url)

print("flights :", flights.shape)
print("airlines:", airlines.shape)

print("--- FLIGHTS SHAPE ---")
print(flights.shape)

print("\n--- FLIGHTS DTYPES ---")
print(flights.dtypes)

print("\n--- FLIGHTS HEAD ---")
print(flights.head())

print("\n--- AIRLINES LOOKUP ---")
print(airlines)

print("=== 1. MISSING VALUES (isna) ===")
print(flights.isna().sum())

print("\n=== 2. NUMERIC SUMMARY (Check for -999 and 0 passengers) ===")
print(flights.describe().T)

print("\n=== 3. TEXT COLUMNS AUDIT (Check whitespace, case sensitivity) ===")
for col in flights.select_dtypes(include='object').columns:
    print(f"\nUnique values in '{col}':")
    print(flights[col].value_counts(dropna=False))

print("\n=== 4. DUPLICATE ROWS ===")
print(f"Exact duplicate rows: {flights.duplicated().sum()}")
if 'flight_id' in flights.columns:
    print(f"Duplicate flight_ids: {flights['flight_id'].duplicated().sum()}")

print("\n=== 5. UNMAPPED AIRLINE CODES ===")
valid_codes = set(airlines['airline_code'].str.strip().str.upper())
flight_codes = set(flights['airline_code'].dropna().astype(str).str.strip().str.upper())
unmatched = flight_codes - valid_codes
print(f"Airline codes in flights but missing from lookup: {unmatched}")

df_clean = flights.copy()
text_cols = df_clean.select_dtypes(include='object').columns
for col in text_cols:
    df_clean[col] = df_clean[col].astype(str).str.strip().str.upper()
df_clean = df_clean.drop_duplicates()
if 'flight_id' in df_clean.columns:
    df_clean = df_clean.drop_duplicates(subset=['flight_id'], keep='first')
if 'delay' in df_clean.columns:
    df_clean['delay'] = df_clean['delay'].replace(-999, np.nan)
if 'passengers' in df_clean.columns:
    df_clean = df_clean[df_clean['passengers'] > 0]
print(f"Original row count : {len(flights)}")
print(f"Cleaned row count  : {len(df_clean)}")
print(f"Excluded rows      : {len(flights) - len(df_clean)}")

airlines_clean = airlines.copy()
airlines_clean['airline_code'] = airlines_clean['airline_code'].astype(str).str.strip().str.upper()

merged = pd.merge(
    df_clean,
    airlines_clean,
    on='airline_code',
    how='left'
)

assert len(merged) == len(df_clean), "Row count changed during merge!"

print("Merge check passed!")
print(f"Total merged rows: {len(merged)}")
print("Unmapped airline names:", merged['airline_name'].isna().sum())

import seaborn as sns
import matplotlib.pyplot as plt
delay_col = next((col for col in ['delay', 'arr_delay', 'dep_delay'] if col in merged.columns), None)
airline_col = next((col for col in ['airline_name', 'airline', 'name'] if col in merged.columns), None)
distance_col = next((col for col in ['distance', 'air_time', 'flight_length'] if col in merged.columns), None)

origin_col = next((col for col in ['origin', 'origin_airport', 'from'] if col in merged.columns), None)
dest_col = next((col for col in ['destination', 'dest', 'to'] if col in merged.columns), None)
if origin_col and dest_col:
    merged['route'] = merged[origin_col].astype(str) + " -> " + merged[dest_col].astype(str)

sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
if airline_col and delay_col:
    airline_perf = merged.dropna(subset=[delay_col]).groupby(airline_col).agg(
        on_time_pct=(delay_col, lambda x: (x <= 0).mean() * 100),
        median_delay=(delay_col, 'median')
    ).reset_index().sort_values(by='on_time_pct', ascending=False)

    sns.barplot(data=airline_perf, x='on_time_pct', y=airline_col, ax=axes[0, 0], palette="Blues_r")
    axes[0, 0].set_title("1. Airline Punctuality Rate (% On-Time)", fontsize=12, fontweight='bold')
    axes[0, 0].set_xlabel("On-Time Percentage (%)")
    axes[0, 0].set_ylabel("Airline")
if 'route' in merged.columns and delay_col:
    route_stats = merged.dropna(subset=[delay_col]).groupby('route').agg(
        flight_count=(delay_col, 'count'),
        median_delay=(delay_col, 'median')
    ).reset_index()

    reliable_routes = route_stats[route_stats['flight_count'] >= 10].sort_values(by='median_delay', ascending=False).head(8)

    sns.barplot(data=reliable_routes, x='median_delay', y='route', ax=axes[0, 1], palette="Reds_r")
    axes[0, 1].set_title("2. Top 8 Worst Delay Routes (Min. 10 Flights)", fontsize=12, fontweight='bold')
    axes[0, 1].set_xlabel("Median Delay (Minutes)")
    axes[0, 1].set_ylabel("Route")
if distance_col and delay_col:
    sns.scatterplot(data=merged, x=distance_col, y=delay_col, alpha=0.5, ax=axes[1, 0], color='teal')
    sns.regplot(data=merged, x=distance_col, y=delay_col, scatter=False, ax=axes[1, 0], color='darkred')
    axes[1, 0].set_title(f"3. {distance_col.title()} vs. Delay", fontsize=12, fontweight='bold')
    axes[1, 0].set_xlabel(distance_col.title())
    axes[1, 0].set_ylabel("Delay (Minutes)")
if delay_col:
    sns.boxplot(data=merged, x=delay_col, ax=axes[1, 1], color='orange')
    axes[1, 1].set_title("4. Distribution of Flight Delays & Extreme Values", fontsize=12, fontweight='bold')
    axes[1, 1].set_xlabel("Delay (Minutes)")

plt.tight_layout()
plt.show()

